### PR TITLE
Added support for cocoapods

### PR DESCRIPTION
**Pull request by tawrahim**
I added support for cocoa pods based on issue https://github.com/neoneye/SwiftyFORM/issues/15

### CODE REVIEW

**Comment by neoneye** [comment]
Awesome. I will look at this when I get home from job

**Comment by neoneye** [comment]
Hi @tawrahim 

Can you transfer SwiftyFORM to me?
My mail is `neoneye AT gmail DOT com`

On the [cocoapods](https://cocoapods.org/pods/SwiftyFORM) page, you are the owner, so I'm having trouble updating it to version 1.

Instructions for doing so are [here](http://guides.cocoapods.org/making/getting-setup-with-trunk#adding-other-people-as-contributors)

Have a great day @tawrahim

**Comment by tawrahim** [comment]
Oh my! I completely forgot and got side track yesterday with work. I'll
look into it ASAP.

Hope you are doing well.

On Mon, Sep 26, 2016 at 8:37 AM, Simon Strandgaard <notifications@github.com

**Comment by tawrahim** [comment]
Done! Sorry that it took me this long. Hectic week at the office.
screen shot 2016-10-01 at 7 02 34 am

**Comment by tawrahim** [comment]
Also I wonder how I completely transfer ownership to you?

**Comment by neoneye** [comment]
I have removed you as owner.

And uploaded [version 1.0.0 to cocoapods.org](https://cocoapods.org/pods/SwiftyFORM)

Thank you @tawrahim for taking time to do this. Much appreciated.

**Pull request merged**
